### ISSUE TITLE
Change guessing logic

### ISSUE THREAD

**Issue by ivanvinski** [ivanvinski/colorinho#20]
## Tasks

* [x] Change guess attempts to one
* [x] On wrong guess, decrease score and regenerate level
* [x] On correct guess, increase score, increase level and regenerate level
