### ISSUE TITLE
Refactor score calculator and calculations

### ISSUE THREAD

**Issue by ivanvinski** [ivanvinski/colorinho#72]
Score calculator and calculations have to be simpler.

## Tasks

* [x] Refactor `~/services/score-calculator.js` into a class. 
* [x] Move `~/services/score-calculator.js` to `~/game` directory
* [x] Change score calculation logic
* [x] Write unit tests for `ScoreCalculator` class
