### ISSUE TITLE
Clean up and refactor architecture

### ISSUE THREAD

**Issue by ivanvinski** [ivanvinski/colorinho#78]
## Summary

Following the first iteration of clean up, I've gotten a better overview of the architecture. More specifically, I've gotten a better overview of how to implement game module to not only improve code quality, but also unit testability. I created UML diagram to think through the architecture of my last iteration of clean up. While I should follow the UML diagram as closely as possible for the game module implementation, the wiring of the module to Vue.js and Vuex should be done based on what I consider the best approach to be once the new game module is implemented. The entire codebase should be easily unit tested.

## Tasks

* [x] Implement the level module
* [x] Implement the tally module
* [x] Implement the storage module
* [x] Implement the utils module
* [x] Implement the game module
* [x] Clean up code and improve tests

## Diagram

![colorinho-diagram](https://user-images.githubusercontent.com/14854181/104533017-d3a26480-5611-11eb-8cd6-b0eba21c40cb.png)
