### ISSUE TITLE
Refactor internationalization module

### ISSUE THREAD

**Issue by ivanvinski** [ivanvinski/colorinho#91]
## Tasks

* [x] Refactor language definition structure
* [x] Enhance loading language definition files
* [x] Enhance i18n module code
* [x] Replace dependency on `vuex-i18n`
