### ISSUE TITLE
Revamp and test user interface

### ISSUE THREAD

**Issue by ivanvinski** [ivanvinski/colorinho#96]
## Tasks

* [x] Refactor and test screens (#101)
* [x] Implement results persistence (#102)
* [x] Refactor and test navbar (#103)
* [x] Refactor and test footer (#104)
* [x] Refactor and test ColorDisplay
* [x] Refactor Background component
* [x] Fix PlayScreen component tests
* [x] Group related components (#106)

### Initial

![colorinho-001](https://user-images.githubusercontent.com/14854181/106357982-c1127580-6309-11eb-8f36-a8c951bf0800.png)

### Playing

![colorinho-002](https://user-images.githubusercontent.com/14854181/106357985-c40d6600-6309-11eb-959a-8bfa5b20d93d.png)
