### ISSUE TITLE
Refactor and test screens

### ISSUE THREAD

**Issue by ivanvinski** [ivanvinski/colorinho#97]
This issue is related to issue #96.

## Tasks

* [x] Implement TallyItem and tests
* [x] Implement Tally and tests
* [x] Implement Timer and tests
* [x] Implement LevelOption and tests
* [x] Implement Level and tests
* [x] Refactor and integrate changes

## Mockup

![colorinho-001](https://user-images.githubusercontent.com/14854181/106357982-c1127580-6309-11eb-8f36-a8c951bf0800.png)
