### ISSUE TITLE
Refactor and test navbar

### ISSUE THREAD

**Issue by ivanvinski** [ivanvinski/colorinho#98]
This issue is related to issue #96.

## Tasks

* [x] Implement Brand and tests
* [x] Implement LanguagePicker and tests
* [x] Implement Navbar and tests

## Mockup

![colorinho-001](https://user-images.githubusercontent.com/14854181/106357982-c1127580-6309-11eb-8f36-a8c951bf0800.png)
