### ISSUE TITLE
Refactor and test footer

### ISSUE THREAD

**Issue by ivanvinski** [ivanvinski/colorinho#99]
This issue is related to issue #96.

## Tasks

* [x] Implement NoticeLink and tests
* [x] Implement VersionLink and tests
* [x] Refactor and test Footer

## Mockup

![colorinho-001](https://user-images.githubusercontent.com/14854181/106357982-c1127580-6309-11eb-8f36-a8c951bf0800.png)
